import faker from 'faker';
import { Factory } from 'rosie';
import { Entities } from "./entities";

export default () => {
  return new Factory()
    .sequence('id')
    .attr('id_str', ['id'], id => id.toString())
    .attr('name', faker.name.findName())
    .attr('screen_name', faker.internet.userName())
    .attr('location')
    .attr('url', faker.internet.url())
    .attr('description', faker.lorem.sentence())
    .attr('entities', Entities().build())
    .attr('protected', false)
    .attr('verified', false)
    .attr('followers_count', faker.random.number())
    .attr('friends_count', faker.random.number())
    .attr('listed_count', faker.random.number())
    .attr('favourites_count', faker.random.number())
    .attr('statuses_count', faker.random.number())
    .attr('created_at', faker.date.past())
    .attr('profile_banner_url', faker.image.image())
    .attr('profile_image_url_https', ['profile_image_url'], url => url)
    .attr('default_profile', false)
    .attr('default_profile_image', false)
    // All attributes beyond this point are deprecated but still available on the users object and will be set to null
    .attr('utc_offset', null)
    .attr('time_zone', null)
    .attr('geo_enabled', null)
    .attr('lang', null)
    .attr('contributors_enabled', null)
    .attr('is_translator', null)
    .attr('is_translation_enabled', null)
    .attr('profile_background_color', null)
    .attr('profile_background_image_url', null)
    .attr('profile_background_image_url_https', null)
    .attr('profile_background_tile', null)
    .attr('profile_image_url', null)
    .attr('profile_link_color', null)
    .attr('profile_sidebar_border_color', null)
    .attr('profile_sidebar_fill_color', null)
    .attr('profile_text_color', null)
    .attr('profile_use_background_image', true)
    .attr('has_extended_profile', false)
    .attr('following', null)
    .attr('follow_request_sent', false)
    .attr('notifications', true)
}