version: '3'

services:
  server:
    environment:
      - DEBUG=0
    restart: always
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    expose:
      - "4466"
  mongo:
    restart: always

volumes:
  mongo: